version: '3'
services:
  db:
    image: postgres:9.2
  web:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "9000:9000"
    command: "lein run"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: "0.0.0.0"
      CLOJURE_ENV: 'development'
